for i in $(seq 1 5000);
do 
    python single_al_cycle.py --DATASETS_PATH ../datasets  --OUTPUT_DIRECTORY tmp/ --SAMPLING random --CLUSTER dummy --NR_QUERIES_PER_ITERATION 10 --START_SET_SIZE 1 --DATASET_NAME dwtc --USER_QUERY_BUDGET_LIMIT 200 --RANDOM_SEED -2 --N_JOBS 20 --AMOUNT_OF_PEAKED_OBJECTS 20&
    python single_al_cycle.py --DATASETS_PATH ../datasets  --OUTPUT_DIRECTORY tmp/ --SAMPLING uncertainty_lc --CLUSTER dummy --NR_QUERIES_PER_ITERATION 10 --START_SET_SIZE 1 --DATASET_NAME dwtc --USER_QUERY_BUDGET_LIMIT 200 --RANDOM_SEED -2 --N_JOBS 20 --AMOUNT_OF_PEAKED_OBJECTS 20&
    python single_al_cycle.py --DATASETS_PATH ../datasets  --OUTPUT_DIRECTORY tmp/ --SAMPLING optimal_forecast --CLUSTER dummy --NR_QUERIES_PER_ITERATION 10 --START_SET_SIZE 1 --DATASET_NAME dwtc --USER_QUERY_BUDGET_LIMIT 200 --RANDOM_SEED -2 --N_JOBS 20 --AMOUNT_OF_PEAKED_OBJECTS 20
    python single_al_cycle.py --DATASETS_PATH ../datasets  --OUTPUT_DIRECTORY tmp/ --SAMPLING optimal_forecast --CLUSTER dummy --NR_QUERIES_PER_ITERATION 10 --START_SET_SIZE 1 --DATASET_NAME dwtc --USER_QUERY_BUDGET_LIMIT 200 --RANDOM_SEED -2 --N_JOBS 10 --AMOUNT_OF_PEAKED_OBJECTS 80
    python single_al_cycle.py --DATASETS_PATH ../datasets  --OUTPUT_DIRECTORY tmp/ --SAMPLING optimal_forecast --CLUSTER dummy --NR_QUERIES_PER_ITERATION 10 --START_SET_SIZE 1 --DATASET_NAME dwtc --USER_QUERY_BUDGET_LIMIT 200 --RANDOM_SEED -2 --N_JOBS 10 --AMOUNT_OF_PEAKED_OBJECTS 160
done
