python fuller_experiment.py --TRAIN_CONVEX_HULL_SAMPLING True --TEST_CONVEX_HULL_SAMPLING True
python fuller_experiment.py --TRAIN_REPRESENTATIVE_FEATURES True --TEST_REPRESENTATIVE_FEATURES True
python fuller_experiment.py --TEST_VARIABLE_DATASET True --TRAIN_VARIABLE_DATASET True
python fuller_experiment.py --TRAIN_NEW_SYNTHETIC_PARAMS True --TEST_NEW_SYNTHETIC_PARAMS True
python fuller_experiment.py --TEST_AMOUNT_OF_FEATURES 2 --TRAIN_AMOUNT_OF_FEATURES 2
python fuller_experiment.py --TEST_VARIABLE_DATASET True --TRAIN_VARIABLE_DATASET True --TRAIN_NEW_SYNTHETIC_PARAMS True --TEST_NEW_SYNTHETIC_PARAMS True --TRAIN_REPRESENTATIVE_FEATURES True --TEST_REPRESENTATIVE_FEATURES True --TEST_AMOUNT_OF_FEATURES 2  --TRAIN_AMOUNT_OF_FEATURES 2
